### ISSUE TITLE
Alpha API Endpoint

### ISSUE THREAD

**Issue by cloneofghosts** [Pirate-Weather/pirateweather#128]
Creating an issue from #93 to make sure this is something that is on your radar.

Basically an Alpha API endpoint would be created accessible to anyone who has paid for access to the dev endpoint and dev would become free to everyone. The alpha endpoint would be where you would test upcoming updates and would be very unstable, Once stable enough it would be pushed up to the dev endpoint for everyone to test and once the bugs are ironed out then it gets pushed live.

The timing would likely depend on how major the update is with minor updates getting the least testing time and major updates having the most update time.

**Comment by alexander0042** [comment]
Progress!!!! As is custom, all the things are trickier than I expected, but I have an incredibly rough V2 alpha framework setup! Right now, there's not much to look at, since it's only a testing endpoint to make sure that things were flowing; however, it represents a ton of key improvements:
1. ~100x faster responses
2. NBM data (although it's not shown yet, it's in there!)
3. Storm distances and directions
4. Short term historic data, fixing the daily high/ low issues.
5. Less interesting, but totally new ingest pipeline that's way more flexible/ maintainable.  

To access it, check out: `https://dev.pirateweather.net/forecastv2/<APIKEY>/<X>,<Y>` 
X and Y are raw grid indexes (I warned it was rough), so keep them between 0-700, and the only data that's returned right now is the -36 hour UTC time for the HRRR model. In the next couple days, I'm going to fix lat/long and expose some of the raw model data (probably current values for everything), so they'll be something to look at! 

I'm curious to see what kinds of speeds you end up getting off it, since I'm seeing ~50 ms right now, but aiming for about 10

**Comment by cloneofghosts** [comment]
@alexander0042 All I'm getting is an Internal Server Error when trying to visit the forecastv2 endpoint

**Comment by alexander0042** [comment]
Still lots of moving parts, so it'll likely come and go over the next couple days. Here's the link that should stay working: `http://piratev2lb-a90c79daaddc2625.elb.us-east-1.amazonaws.com:8000/forecastv2/<APIKEY>/<X>,<Y>` . Note that there's a port number in there for now,

**Comment by cloneofghosts** [comment]
@alexander0042 Thanks that link works. The first link you sent is giving me a "An invalid response was received from the upstream server" error when I try to visit it now.

Seems to have a bit more delay in loading but that might be due to the server? I see a DataReadTime flag but it doesn't seem to contain any unit of time but I assume since it's <0 it's fast?

**Comment by cloneofghosts** [comment]
Since there's a 2.0 changelog now I think it makes sense to close this issue. You can update that whenever you get something working on the new version.

**Comment by cloneofghosts** [comment]
@alexander0042 Just wondering if there's been more progress on this at all. When I visit forecastv2 on the dev URL I get:

```
{
"message": "An invalid response was received from the upstream server"
}
```

While the second link works I haven't really seen many changes since the first version went live. Is this because you've been busy rather than you haven't actually pushed up any updates since then?
