### ISSUE TITLE
Differnce between MerrySky and BriefSky

### ISSUE THREAD

**Issue by patel-jeel92** [Pirate-Weather/pirateweather#142]
### Describe the issue

When querying the weather info between two apps (MerrySky and BriefSky) I can see the two apps showing different conditions for a given day. For example, the merry sky ui for Friday shows 

![image](https://github.com/Pirate-Weather/pirateweather/assets/20840348/3648a54f-7548-4be1-9ccb-c3724ba3ac5e)

where as briefsky shows 
![image](https://github.com/Pirate-Weather/pirateweather/assets/20840348/7658b46c-e17c-4649-b07a-23ae4ded8b48)

As you can see that merrysky distinguishes between light rain and rain throughout the day. However briefsky doesnt.

Looking at the response for the hourly data at 30097 (no lat long provided for privacy reasons) i dont see any summaries that have light rain so not sure how merry sky is accomplishing this? 

### Acknowledgements

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
From what I can tell MerrySky does their own processing on the hourly data to categorize them as Light Rain/Rain/etc. whereas BriefSky is showing the data directly from the API.

There is already an issue open to implement text summaries/descriptions (#48) but it seems to be more of a long-term goal so I wouldn't expect it as part of the V2 update. I did mention in that issue that maybe getting the translations/descriptions working would be a good first step and then the summaries can come later.

Another thing to note is that MerrySky does have caching enabled which is why there may be differences between the two outputs as it seems like BriefSky uses your own API key and gets the most up-to-date data availble.

**Comment by patel-jeel92** [comment]
I looked at the dark sky translation repo. I am not sure if i understand the concept. Seems like their API was producing structured expressions that were then used to get a human readable summaries from the translation files (en.json) for example. Would pirate weather need to create the structured expression for this to work?

**Comment by cloneofghosts** [comment]
Yes, DarkSky used the translation repo in their app to produce the summaries/descriptions. We don't know how they used the repo in their API since the code that produced the API isn't open source.

@alexander0042 would need to write the code in order to produce the human readable summaries using the translation repo. I believe he mentioned that he was working on creating the human readable summaries before he started work on V2 of the API.

**Comment by patel-jeel92** [comment]
I see, Do you know if there is a way to run pirate weather locally or self host it with the complete architecture? Maybe if that was possible we could have other people look into it

**Comment by cloneofghosts** [comment]
Unfortunately there is no way to self-host or run the API locally at the moment. There is this issue #11 and it's part of the V2 road map.

**Comment by patel-jeel92** [comment]
@alexander0042 any plans to use https://github.com/blaylockbk/Herbie? seems like this would help with processing the grib files?

**Comment by alexander0042** [comment]
Hey, thanks for opening this issue, and also cluing me into Briefsky, which I hadn't seen before!

To answer your initial question- I suspect the reason they're different is because Merrysky always calls the midnight forecast, which is a clever workaround to the daily high/ daily low bug; however, sometimes leads to differences in data throughout the day. V2 addresses this (including using the wonderful Herbie), so should fix this problem soon!

The self hosting question is a long running one, My goal here is to make the code open so people know where their weather data is coming from; hpowever, since everything is so tied into AWS actual self hosting is going to be very tricky to make possible. To be honest, there are some really cool AI forecasting products coming online now, and I think that's a better approach for anyone that wants to self host something. I can't think of a good use case of self hosting a weather API of the model data is still being provided by the cloud. 

And text descriptions are high on the list, just need to code it! It'll be after V2, but no too far after

**Comment by patel-jeel92** [comment]
@alexander0042 Thanks for the input! I will look into how to all the midnight forecast to address the bug until V2 is out. 

Also the only missing part from the open source is how to extract data from the processed file when a query for a certain latitute and longitude comes in. I dont know how to how that process is being done and it would be cool to learn.
