### ISSUE TITLE
Precipitation Probability >0 with no accumulation

### ISSUE THREAD

**Issue by cloneofghosts** [Pirate-Weather/pirateweather#225]
Thanks.  My results have been looking good too for the past 10 days or so.  However, right now I'm seeing 19% probability and 0 for accumulation on day 0.  Does that sometimes happen or should accumulation always be >0 if probability is >0%?

_Originally posted by @jhemak in https://github.com/Pirate-Weather/pirateweather/issues/205#issuecomment-2113473313_

**Comment by cloneofghosts** [comment]
I created a new issue for you from your comment @jhemak. I think that may happen sometimes but I'll also ping @alexander0042 to confirm for you.

**Comment by cloneofghosts** [comment]
From my experience you can get precipitation probability >0 without any precipitation if the probability is low enough. I've used other APIs in the past where it has a probability >0 with no precipitation so it's not completely unheard of for it to happen.

Will ping @alexander0042 again to confirm if this is intended behaviour

**Comment by alexander0042** [comment]
Thanks for the updated ping! Was travelling for a bit there, so behind on this.

Yes, I can confirm that you can get a probability >0 with no precipitation. It's because they're sometimes coming from different sources or different models, and the ensemble will sometimes show a chance of something but not confident in any amount. Basically, one is probabilistic, the other deterministic. Should update the docs though, so thanks for creating that issue!
