### ISSUE TITLE
Pressure values innacurate by significant amount

### ISSUE THREAD

**Issue by speedbird182** [Pirate-Weather/pirateweather#269]
### Describe the bug

The Pressure Sensor values are incorrect by a significant amount (~20 hPa).  

### Expected behavior

This shows the pressure as taken from Pirate Weather:
![Screenshot 2024-07-18 at 15-57-56 Overview – Home Assistant](https://github.com/user-attachments/assets/bd15498f-3127-4427-b3ae-0527a5031f15)

Where as this is the actual current pressure from Met.No and the UK Met Office:
![Screenshot 2024-07-18 at 15-58-27 Overview – Home Assistant](https://github.com/user-attachments/assets/173c7da5-f8f7-443f-96a8-cc691910a90e)

### Actual behavior

Current pressure should match (or be very close to) actual readings from the UK met office.

### API Endpoint

Production

### Location

Liskeard, Cornwall

### Troubleshooting steps

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
Thanks for the report. What's happening here is the `pressure` values displayed in Pirate Weather is surface-level pressure whereas most sites use sea-level pressure for their pressure values which is what Dark Sky used for pressure values as reported in #265 

Will ping @alexander0042 to look into this but it should just be a case of switching the data to use sea-level pressure instead of surface-level pressure.

**Comment by alexander0042** [comment]
This is a great catch, and I can't believe I've never noticed it before! I'll get pressure switched over to MSLP in the next update, which should fix this problem

**Comment by cloneofghosts** [comment]
This has been fixed in V2.1.1 of the API which released today.
