### ISSUE TITLE
Fix HTML on Terms page

### ISSUE THREAD

**Issue by mbomb007** [Pirate-Weather/pirateweather#299]
### Describe the issue

https://pirate-weather.apiable.io/terms

> There is no guarantee that this service will:
>
> Work when you try to use it Continue to work Produce accurate results Not do anything crazy Keep the same API key limits

It looks like the content should be an ordered or unordered list. However, it's just a single paragraph. The other sections are the same, having odd spacing (or lack thereof).

It would also be nice if the Terms would hyperlink to the privacy policy.

The privacy policy has similar formatting issues. https://pirate-weather.apiable.io/privacy

### Acknowledgements

- [X] I have searched this repository to see if the issue has already been reported.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
Thanks for reporting this! Only @alexander0042 has the ability to update these docs but it should now be on the radar to get these all fixed up.

The terms and conditions text seems to have been taken from the old getting started page before the docs were updated https://github.com/Pirate-Weather/pirateweather/blob/main/DevPortal/custom-content/content-fragments/GettingStarted.md#terms-and-conditions. 

Also on the Privacy Policy page I see a bunch of links which takes you to a Termly page which you have to sign up for. I assume these are meant to be jump links to different sections on the page?

**Comment by alexander0042** [comment]
Sometimes the fact that my background is civil engineering, not business (or computer science) is painfully obvious! I used an online generator for those, since I figured "these seem like the sorts of things I should include", but never stopped to check the formatting, so I'll fix it now!

For the record, the goal of the terms of service is to say: while this service has been around for a couple years and is broadly stable, glitches, incorrect data, or downtime may occur, and accordingly, unless we have a contract in place, there is no formal guarantee about the results. 

Re: Privacy policy, the only data logged by the API is the latitude and longitude of the request. These get saved for 3 days to help with debugging, and are then flushed. Everything else is now handled by Apiable, and they have a wonderfully comprehensive privacy policy.

**Comment by cloneofghosts** [comment]
It's been a few days and while I see that it's mostly fixed there still are a few issues:

Terms of Service the Limitation of Liability section is one giant paragraph and is hard to read. The one in the getting started I linked to has a few paragraphs and another section.

The privacy page everything after the CCPA Privacy Notice still seems to have not been fixed yet.

**Comment by cloneofghosts** [comment]
@alexander0042 Just bumping this as a reminder to finish fixing both pages as I noticed that this still hasn't been fixed yet.

**Comment by alexander0042** [comment]
Up, updated! Also added them to the repo for future improvements
