### ISSUE TITLE
A couple of Time Machine Issues

### ISSUE THREAD

**Issue by cloneofghosts** [Pirate-Weather/pirateweather#330]
### Describe the issue

I had posted this in #130 but I figure I'd post it here. Most of this is an issue when accessing the ERA5 dataset and not the PW archive

1. When including a time parameter the connection is not secure
2. `windGust` should be right below `windSpeed`
3. `precipIntensity` only appears on the currently block and nowhere else
4. The icon calculation seems to not be working correctly still

```
{
  "time": 1714521600,
  "icon": "cloudy",
  "summary": "Cloudy",
  "precipAccumulation": 0,
  "precipType": "rain",
  "temperature": 7.27,
  "apparentTemperature": 6,
  "dewPoint": 4.26,
  "pressure": 1014.2,
  "windSpeed": 7.21,
  "windBearing": 73.7,
  "cloudCover": 0.62,
  "snowAccumulation": 0,
  "windGust": 14.23
},
```
5. Negative longitudes do not display correctly. -75 displays as 285
6. When accessing the PW archive there are extra blocks/summaries not present when you access the ERA5 data. Minutely, alerts, flags, hourly/daily summaries probably shouldn't appear
7. In line with above the extra fields that are shown when accessing the PW archive should probably be behind a query string? Would be better to keep things consistent between ERA5 and the PW archive.
8. `precipAccumulation` is rounded to two decimal places instead of four
9. The ERA5 data has a `snowAccumulation` data point which shouldn't be there

### Acknowledgements

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have not included my API key anywhere in my issue.
- [X] I have written an informative title.

**Comment by alexander0042** [comment]
Great clean-up catches here! To address in detail:
1. Weird Cloudfront issue, seems to be fixed now.
2. Fixed!
3. This is intentional. ERA5 doesn't have historic instant intensity, only accumulations, so everything is per hour. For currently, the hourly average is used since current accumulation doesn't make sense, but I think it's clearer to label it as an accumulation in the other blocks.
4. Fixed to align with forecast!
5. Fixed!
6. Mostly fixed! Agree with the consistency- I removed minutely and alerts, and added flags into older requests to keep it consistent, as well as removed missing fields from PW Archive requests.
7. Agreed! Added a new query param called "tmextra" to show all the data in the PW Archive
8. I really like trying to show snow vs rain, so since this data point is in the NCAR archive and the PW one, I figured it was worth including!

**Comment by cloneofghosts** [comment]
> 3. This is intentional. ERA5 doesn't have historic instant intensity, only accumulations, so everything is per hour. For currently, the hourly average is used since current accumulation doesn't make sense, but I think it's clearer to label it as an accumulation in the other blocks.

Isn't `precipIntensity` just `precipAccumulation` multiplied by 10 to convert from cm to mm? You could probably just do the same here no?

> 8. I really like trying to show snow vs rain, so since this data point is in the NCAR archive and the PW one, I figured it was worth including!

The only reason I mentioned it is that Dark Sky never had a `snowAccumulation` field in their data points.

**Comment by alexander0042** [comment]
Ok, added intensity back in, should propagate out in the next hour or so!

**Comment by alexander0042** [comment]
You are amazing with these sorts of catches! It was just missed, fixing it now

**Comment by cloneofghosts** [comment]
Just checked and things are looking good now so can close.
