### ISSUE TITLE
Alert expires time can come before the alert start time.

### ISSUE THREAD

**Issue by mbomb007** [Pirate-Weather/pirateweather#353]
### Describe the bug

This is likely an upstream problem with the NWS, but I have an alert where the start time comes after the expiration time.

### Expected behavior

An alert's start time comes before the time it expires.

### Actual behavior

The API is using the `<onset>` property for the start time, rather than the `<effective>` property, which is probably what it should use.

This is the data from the NWS Alert .cap file:

```xml
        <effective>2024-10-16T02:46:00-05:00</effective>
        <onset>2024-10-17T11:00:00-05:00</onset>
        <expires>2024-10-16T13:00:00-05:00</expires>
        <headline>Fire Weather Watch issued October 16 at 2:46AM CDT until October 17 at 7:00PM CDT [...]</headline>
```

### API Endpoint

Production

### Other details

https://api.weather.gov/alerts/urn:oid:2.49.0.1.840.0.909ae5ab6113a0467ac3b38120588e2c04187ad6.001.3.cap

### Troubleshooting steps

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have not included my API key anywhere in my issue.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
It might be a NWS issue but will ping @alexander0042 to look into this and get back to you.

**Comment by alexander0042** [comment]
Sorry that I missed this- you're spot on about the onset time, I just grabbed the wrong variable there, so that's been corrected. 

The line breaks were actually an intentional decision, Dark Sky didn't return line breaks (See: [Issue 38 from the HA repo](https://github.com/Pirate-Weather/pirate-weather-ha/issues/38), so I wanted to keep it consistent with that. However, I see why it's a pain to not have them, and agree it would be better if they were there! You should see them live shortly, and I'll keep an eye out to see if it breaks anything
