### ISSUE TITLE
`precipType` rain when temperature below freezing

### ISSUE THREAD

**Issue by cloneofghosts** [Pirate-Weather/pirateweather#382]
### Describe the issue

Noticed this morning in my HA install that the API is showing several hours of rain when the temperature is below freezing. I'm aware that this could be freezing rain but I thought that the API would show the `precipType` as sleet and not rain.

I've included one of the hours that is showing the issue I'm seeing:

```
  "time": 1733745600,
  "summary": "Drizzle",
  "icon": "rain",
  "precipIntensity": 0.0847,
  "precipProbability": 0.38,
  "precipIntensityError": 0.0928,
  "precipAccumulation": 0,
  "precipType": "rain",
  "temperature": -2.15,
```

NOTE: I used the dev endpoint to demonstrate this as the live endpoint isn't showing the icon/summary as rain for some reason.

### Acknowledgements

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have not included my API key anywhere in my issue.
- [X] I have written an informative title.

**Comment by alexander0042** [comment]
Interesting- what was the production endpoint showing as- snow? Or nothing?

**Comment by cloneofghosts** [comment]
> Interesting- what was the production endpoint showing as- snow? Or nothing?

It was showing as `fog` earlier but now its showing as Partly Cloudy.

```json
  "time": 1733745600,
  "icon": "partly-cloudy-night",
  "summary": "Partly Cloudy",
  "precipIntensity": 0.0423,
  "precipProbability": 0.45,
  "precipIntensityError": 0.0456,
  "precipAccumulation": 0,
  "precipType": "rain",
  "temperature": -1.9,
```

**Comment by cloneofghosts** [comment]
@alexander0042 I checked both endpoints this morning and they are both showing rain and the `precipAccumulation` is non-zero now. It could be that this is supposed to be freezing rain and the PW API is showing it as rain?

**Comment by alexander0042** [comment]
The accumulation is probably because it comes from a different variable, so can show zero if it's not expected to accumulate to anything; although it is a little unusual. Do you remember what time you checked it at, since I'm seeing snow now

**Comment by cloneofghosts** [comment]
I just checked both endpoints and I'm still seeing the issue. The first instance of this occurs on Monday, 9 December 2024 06:00:00 EST

Live:
```json
"time": 1733742000,
"icon": "rain",
"summary": "Rain",
"precipIntensity": 0.1266,
"precipProbability": 0.34,
"precipIntensityError": 0.2494,
"precipAccumulation": 0.0127,
"precipType": "rain",
"temperature": -0.29,
```

Dev:
```json
"time": 1733742000,
"summary": "Drizzle",
"icon": "rain",
"precipIntensity": 0.1266,
"precipProbability": 0.34,
"precipIntensityError": 0.2494,
"precipAccumulation": 0.0127,
"precipType": "rain",
"temperature": -0.29,
```

**Comment by alexander0042** [comment]
Ok so dug into this a little, and it's kind of interesting. What's happening (I believe) is that because NBM is a blend of different ensemble models, it's not always consistent in how it predicts this stuff. So if a few inputs are showing a <0 temperature with minimal precipitation, and a few inputs are showing >0 temps with precipitation, we can get a <0 average temp with a rain type. 

I pulled the raw data and made a quick plot that gives an idea of what's going into Pirate Weather here:

![image](https://github.com/user-attachments/assets/14794cf5-d453-46ae-a86b-8e67fcf82da2)

So now that I'm confident at least all the processing is happening correctly, the better question is what to do about it. I agree that this doesn't really make sense, but I'm also insistent to predict freezing rain if that isn't explicitly called for. Maybe just flip it from rain to snow if temperature is below zero and visa vera?

**Comment by cloneofghosts** [comment]
Ah, so differences in what the ensemble models forecast is whats causing the issue. It looks a bit weird but it might just be something that can happen normally? I see Environment Canada is forecasting -3C with chance of showers on Sunday:
![image](https://github.com/user-attachments/assets/d9395c89-68f5-4d66-8334-29a4a19e0a4b)
