### ISSUE TITLE
Bad address search

### ISSUE THREAD

**Issue by cliffclick** [Pirate-Weather/pirateweather#386]
### Describe the bug

For several years, my home address "Adams Ridge" search using MerrySky would give me the weather for ... my home.
Starting some weeks ago, it now reports "Adams Ridge, Shrewbury" which is worlds apart.  Giving my full address:
Adams Ridge, Los Gatos, CA", gives me a "address not found"

### Expected behavior

I expect to see weather for "Adams Ridge, Los Gatos CA".

### Actual behavior

Address not found.

### API Endpoint

Production

### Location

Los Gatos, CA

### Other details

Sorry if this is the wrong place to file.  I cannot figure out how to file a bug with merrysky.  :-(

### Troubleshooting steps

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have not included my API key anywhere in my issue.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
Merry Sky does have a [FAQ page](https://merrysky.net/faq) where they have the [feedback@merrysky.net](mailto:feedback@merrysky.net) email address listed. I'd recommend sending an email to that email address so the Merry Sky developers can fix your issue.

Just an FYI I edited your post to remove the address you posted as it isn't a good idea to post your full address online. When sending an email to the Merry Sky developers I'd recommend sending them Adams Ridge, Los Gatos, CA instead of your full address.

**Comment by cliffclick** [comment]
Thanks!
