### ISSUE TITLE
Node Red node

### ISSUE THREAD

**Issue by andreapx** [Pirate-Weather/pirateweather#81]
Hi Alexander, sorry, this is not an issue.
Maybe you can fork [this DarkSky Node Red node](https://flows.nodered.org/node/node-red-node-darksky) and make it compatible with your service??? 😘

**Comment by jonhanford** [comment]
I will +1 this since that would make life a bit easier! 

But I'll also note, it's pretty straightforward to just use a URL node to use this api with node-red. 
Have it return a parsed json opject, and You can use a change node afterwards to move msg.payload to msg.data and any parameters you want exposed directly under payload to wherever they ought to be. Put that in a subflow and it's a pretty drop-in replacement. 

Been using it that way for a bit. Works fine.

**Comment by alexander0042** [comment]
This is a great idea, and should be an easy change! I've never used Node Red, but heard a lot of really positive things about it, so would love to be added to their repo. 

I made a quick fork here <https://github.com/alexander0042/node-red-web-nodes>, replacing the url string from darksky.net to pirateweather.net. If I've set things up correctly, then this should be all that's needed (along with a new API key). Is there an easy way for you to test if this works? I'm thinking I would also have to rename/ remap the rest of the Dark Sky strings before I submit it as a PR

**Comment by andreapx** [comment]
I don't know what that web node is, but there is a [DarkSky node](https://flows.nodered.org/node/node-red-node-darksky) ([GitHub page](https://github.com/node-red/node-red-web-nodes)) you could fork

**Comment by andreapx** [comment]
Ahahaha, sorry, I've read "node-red-web-nodes" and I thought you used a web node! :)
I'll test it

**Comment by cloneofghosts** [comment]
I noticed that this one went stale without a reply from @andreapx. Did you get a chance to test the forked repo at all?

**Comment by cloneofghosts** [comment]
Even after the ping there hasn't been any updates here I'm going to close this one again. If you get a chance to test then feel free to re-open it.
